apiVersion: v1
kind: Service
metadata:
  name: bpay-site-{{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: bpay-site-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000