# Имена переменных в настройках

MANAGER_TELEGRAM_LINK = "https://t.me/syst3mat1c"

GOOGLE_RECAPTCHA_SECRET_KEY = 'GOOGLE RECAPTCHA SECRET KEY'
GOOGLE_RECAPTCHA_SITE_KEY = 'GOOGLE RECAPTCHA SITE KEY'

ORDER_STATUS_NEW = 'new'
ORDER_STATUS_PAID = 'paid'
ORDER_STATUS_DONE = 'done'
ORDER_STATUS_OVERDUE = 'overdue'
ORDER_STATUS_CANCEL = 'cancel'

ORDER_TYPE_BALANCE_TO_EXTERNAL = "BALANCE_TO_EXTERNAL"
ORDER_TYPE_EXTERNAL_TO_BALANCE = "EXTERNAL_TO_BALANCE"
ORDER_TYPE_EXTERNAL_TO_EXTERNAL = "EXTERNAL_TO_EXTERNAL"

ORDER_ORIGIN_MANUAL_FROM_SITE = "MANUAL_FROM_SITE"

SETTINGS_OVERDUE_TIME = 'overdue_time'
SETTINGS_TGBOT_LINK = 'bot_link'
SETTINGS_CONTACT_FOOTER_BLOCK_PAGE = 'contact_footer_block_page'
SETTINGS_INFO_FOOTER_BLOCK_PAGE = 'info_footer_block_page'


PRIVATE_API_USER_EMAIL = "bot@chngbot.ru"
PRIVATE_API_USER_PASSWORD = "bot_access_password"

ENCRYPT_KEY = b'1DrCHTrnmHyrg_eowYwjPICeqj0cTs-I-wzxxbijOPM='
BINANCE_API_URL = 'https://api.binance.com/api/v3/ticker/price'
